# Site
repository: ohjinnoo/ohjinnoo.github.io
# favicon: images/favicon.ico

# Personal info
name: 오진우
title: Java 벡엔드 개발자 엔지니어
email: dhwlsdn741@gmail.com

github_username:  jwoo-o

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 6년 차 백엔드 개발자로 **Mau 100만인 웨이팅, 포스/키오스크 주문 서비스 시스템**, <br/> 
  **8억건의 EP상품데이터**를 수집, 검색서비스 시스템, **Dau 30만인 시스템**에 API/Batch/인프라 구축 등을 해왔습니다.<br/>
  주도적으로 업무를 리스팅 하고 반복되는 일을 자동화하여 비효율적인 프로세스를 개선하는 일을 좋아합니다. <br>
  여기저기 분산되어 있는 모니터링을 한곳으로 통합하거나, 입사, 휴가, 자산관리를 원할하게 관리 할 수 있도록 <br>
  백오피스를 개발하여 인사/총무팀 업무를 개선 시킨 경험이 있습니다.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
